### ISSUE TITLE
Grid. Filter work only once.

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#84]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Grid with local data binding.  enable-data-filter =true
`<amexio-datagrid 
		  [title]="'Sample Grid'" 
		  [page-size] = "10" 
		  [enable-checkbox]="false" 
		  [enable-data-filter]="true"
		  [data]="examInfoArray" 
		  (selectedRowData)="onSelect($event)" 
		  (rowSelect)="onSelect($event)"> 
          <amexio-data-table-column [data-index]="'theCert_name'" [data-type]="'string'" [hidden]="false" [text]="'XXXXXX'"></amexio-data-table-column> 
		</amexio-datagrid> `
After reload data from service to examInfoArray I use filter field. It's work OK.  But when I clear text in filter field I have no changes in grid.
![filter1](https://user-images.githubusercontent.com/16590085/40731709-4cef28ea-643a-11e8-91dd-bb31cdabddc2.png)
![filter2](https://user-images.githubusercontent.com/16590085/40731713-4d829ee0-643a-11e8-9962-10ea3c92bd91.png)
![filter3](https://user-images.githubusercontent.com/16590085/40731714-4dca5c94-643a-11e8-8693-614eeaa4aba8.png)

## Expected behavior

Grid content restore on clear filter text.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by rashmithakkar** [comment]
@baminmru plz take a look at its implementation in API docs at http://amexio.org/test/api/v4.2/#/filter-grid

**Comment by baminmru** [comment]
This sample use  http for retrive data:

 [data-reader]="'data'"
  [http-url]="'assets/data/componentdata/datagridgroupby.json'"
  [http-method]="'get'"

Try to use direct data binding
  [data]="some_array"

**Comment by sagarthecook** [comment]
We will check and get back to you.

**Comment by rashmithakkar** [comment]
@baminmru  We have solved the bug. You will find it in next update..

**Comment by ketan-gote** [comment]
@baminmru Issue has been fixed and is part of 4.2.2 release.

**Comment by baminmru** [comment]
I check this error with Amexio 4.2.3    
Error not fixed yet.

**Comment by sagarthecook** [comment]
@Baminmru we will recheck this issue and get back to you

**Comment by rashmithakkar** [comment]
We are very sorry for inconvenience.
You will find it resolved in next update.

**Comment by sagarthecook** [comment]
@baminmru We have fixed this issue in latest version v4.2.6 please check and close this issue

**Comment by baminmru** [comment]
#I have updated my project to Amexio version 4.2.6 now the filter does not work at all. If I enter any letter in the filter field, the contents of the grid just disappear.

**Comment by ketan-gote** [comment]
@baminmru  - Have create stackblitz example with filter and direct data binding, please check below link. Let me know if you have anymore issues.

https://stackblitz.com/edit/amexio-v4-filter-grid-sr6cxg

**Comment by baminmru** [comment]
I looked at Your example, Yes it works. I'm trying to understand why it doesn't work in my version.

**Comment by sagarthecook** [comment]
@baminmru can you share your code snipped and package JSON file.

**Comment by baminmru** [comment]
Hi!  I do some researches in filter behaviour. And now I've solved my problem.
In my code I change data dynamically after component load.
Data field is changing after control rendered.
In this case filterCloneData of datagridcomponent not set to actual data. So I change function setChangeData to:
`
setChangeData(httpResponse: any){
    this.setSelectedFlag(httpResponse);
    
	if (this.groupby) {
      this.cloneData = JSON.parse(JSON.stringify(httpResponse));
    }
    if (this.enabledatafilter) {
      this.filterCloneData = JSON.parse(JSON.stringify(httpResponse));
    }
    if (this.globalfilter) {
      this.filterCloneData = JSON.parse(JSON.stringify(httpResponse));
    }
    if (this.groupby) {
      this.setColumnData();
    }
   if (!this.groupby) {
      this.renderData();
    }
    this.totalPages = this.pageNumbers.length;
    this.mask = false;
  }`

And also I made  little change in function  getFilteredData

` 
getFilteredData(filteredObj: any) {
    let status = false;
    if (filteredObj.length > 0) {
      this._data = [];  // original code is:  this.data = [];
.....
`
